# Generated by Django 4.0.4 on 2022-06-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_rename_name_order_name_receive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.IntegerField(),
        ),
    ]
