# Generated by Django 4.0.4 on 2022-06-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='pro_id',
            field=models.IntegerField(),
        ),
    ]
