# Generated by Django 4.0.4 on 2022-06-19 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
