# Generated by Django 4.0.4 on 2022-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customeruser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='avatar',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
