# Generated by Django 4.0.4 on 2022-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customeruser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='phone_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
