# Generated by Django 4.0.4 on 2022-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_view',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
